version: '3'

volumes:
  aws-test-data:
    driver: local

services:
  postgres:
    image: postgres:11
    container_name: aws_test
    volumes:
      - aws-test-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_USER=test
